<?php
/**
 * @file
 * Page callbacks for the High Country Craft Food and Beverage Festival's website.
 */

/**
 * Page callback for the homepage.
 */
function hcbf_home() {
  return theme('hcbf_home');
}

/**
 * Page callback for the breweries page.
 */
function hcbf_about() {
  return theme('hcbf_about');
}

/**
 * Page callback for the breweries page.
 */
function hcbf_breweries() {
  return theme('hcbf_breweries');
}

/**
 * Page callback for the sponsors page.
 */
function hcbf_sponsors() {
  return theme('hcbf_sponsors');
}

