<?php
/**
 * @file
 * The core module for the High Country Craft Food and Beverage Festival's website.
 */

/**
 * Implements hook_menu();
 */
function hcbf_core_menu() {
  $items = array();

  $items['admin/config/hcbf'] = array(
    'title' => 'High Country Beer Fest',
    'description' => 'High Country Beer Fest configuration.',
    'position' => 'right',
    'weight' => -20,
    'page callback' => 'hcbf_core_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'hcbf_core.admin.inc',
  );

  $items['admin/config/hcbf/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'A dashboard for the High Country Beer Fest website.',
    'page callback' => 'hcbf_core_dashboard',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'hcbf_core.admin.inc',
  );

  $items['admin/config/hcbf/core'] = array(
    'title' => 'Core config',
    'description' => 'Configuration for the High Country Beer Fest site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hcbf_core_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'hcbf_core.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme();
 */
function hcbf_core_theme() {
  $themes = array();

  $themes['hcbf_core_dashboard'] = array(
    'variables' => array(
      'festival' => NULL,
    ),
    'template' => 'templates/hcbf_core_dashboard',
  );

  return $themes;
}

/**
 * Gets a count of the currently published breweries.
 */
function hcbf_get_brewery_count() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'hcbf_brewery')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_hcbf_brewery_accepted', 'value', 'yes', '=')
    ->propertyOrderBy('title', 'ASC');

  $result = $query->execute();
  return count(array_keys($result['node']));
}

/**
 * Generates a box.
 *
 * @param $box array
 *   A keyed array that describes the box and it's contents.
 *
 *   Usage:
 *      $box = array(
 *        'name' => 'name',
 *        'wrapper_classes' => array('wrapper-1', 'wrapper-2'),
 *        'icon' => 'fa-iconname',
 *        'title' => 'A string for a heading',
 *        'content' => array(
 *          '#type' => 'markup',
 *          '#markup' => 'Text content',
 *          '#prefix' => '<p>',
 *          '#suffix' => '</p>',
 *        ),
 *       );
 *      $box_array = hcbf_link_box_generator($box);
 *
 */
function hcbf_link_box_generator($box) {

  // Build the wrapper class array
  $wrapper_classes = array('box-wrapper');
  if (array_key_exists('name', $box) && !empty($box['name'])) {
    $wrapper_classes[] = $box['name'] . '-wrapper';
  }

  // Add additional classes
  if (array_key_exists('wrapper_classes', $box) && !empty($box['wrapper_classes'])) {
    $wrapper_classes = array_merge($wrapper_classes, $box['wrapper_classes']);
  }
  $wrapper_classes = implode(' ', $wrapper_classes);

  // Make sure the icon is set
  $box_icon = 'fa-circle-o-notch fa-spin';
  if (array_key_exists('icon', $box) && !empty($box['icon'])) {
    $box_icon = $box['icon'];
  }

  // Make sure the title is set
  $box_title = t('Box title');
  if (array_key_exists('title', $box) && !empty($box['title'])) {
    $box_title = $box['title'];
  }
  $box_title = t('Box title');
  if (array_key_exists('title', $box) && !empty($box['title'])) {
    $box_title = $box['title'];
  }

  // Get the box content
  $box_content = array(
    '#type' => 'markup',
    '#markup' => 'Default box content',
    '#prefix' => '<p>',
    '#suffix' => '</p>',
  );
  if (array_key_exists('content', $box) && !empty($box['content'])) {
    $box_content = $box['content'];
  }

  $dom = array(
    array(
      '#type' => 'markup',
      '#prefix' => '<div class="' . $wrapper_classes . '">',
      '#suffix' => '</div>',
      array(
        '#type' => 'markup',
        '#prefix' => '<div class="text-center">',
        '#suffix' => '</div>',
        array(
          '#type' => 'markup',
          '#prefix' => '<i class="icon fa ' . $box_icon . ' fa-5x">',
          '#suffix' => '</i>',
        ),
      ),

      array( '#type' => 'markup',
        '#prefix' => '<div class="page-header">',
        '#suffix' => '</div>',
        array(
          '#type' => 'markup',
          '#markup' => $box_title,
          '#prefix' => '<h2 class="text-center">',
          '#suffix' => '</h2>',
        ),
      ),
      $box_content,
    ),
  );

  return $dom;
}

/**
 * Generates the 'The Festivities' box.
 *
 * @return array
 *   A renderable array that contains the content for the The Festivities page
 */
function hcbf_the_festivities_box() {
  $brewery_count = hcbf_get_brewery_count();
  return hcbf_link_box_generator(
    array(
      'name' => 'the-festivities',
      'icon' => 'fa-beer',
      'title' => t('The Festivities'),
      'content' => array(
        '#type' => 'markup',
        '#prefix' => '<div class="box-content">',
        '#suffix' => '</div>',
        array(
          '#type' => 'markup',
          '#markup' => 'Join us and ' . $brewery_count . ' breweries from around the world at the High Country Fairgrounds in Boone, North Carolina on Saturday, August 30, 2014 from 3:00 pm to 7:00 pm to sample a variety of craft beer, craft food, educational seminars, and live music.',
          '#prefix' => '<p class="text-center">',
          '#suffix' => '</p>',
        ),
      ),
    )
  );
}

/**
 * Generates the 'Get involved' box.
 *
 * @return array
 *   A renderable array that contains the content for the "buy tickets" box.
 */
function hcbf_get_involved_box() {
  return hcbf_link_box_generator(
    array(
      'name' => 'get-involved',
      'icon' => 'fa-users',
      'title' => t('Get involved'),
      'content' => array(
        '#type' => 'markup',
        '#prefix' => '<div class="box-content">',
        '#suffix' => '</div>',
        array(
          '#type' => 'markup',
          '#markup' => 'We\'re looking for volunteers to help us put on the 7<sup>th</sup> annual High Country Beer Fest.',
          '#prefix' => '<p class="text-center">',
          '#suffix' => '</p>',
        ),
        array(
          '#type' => 'markup',
          '#prefix' => '<div class="text-center">',
          '#suffix' => '</div>',
          array(
            '#type' => 'markup',
            '#markup' => l('<i class="fa fa-thumbs-up"></i> ' . t('I\'d like to get involved'), 'volunteer', array(
              'attributes' => array(
                'class' => array('btn', 'btn-success', 'btn-lg'),
              ),
              'html' => TRUE,
            )),
          ),
        ),
      ),
    )
  );
}

