<?php
/**
 * @file
 * The core module for the High Country Craft Food and Beverage Festival's website.
 */

/**
 * Implements hook_menu()
 */
function hcbf_home_menu() {
  $items = array();

  $items['home'] = array(
    'title' => t('Home'),
    'page callback' => 'hcbf_home',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'hcbf_home.pages.inc'
  );

  return $items;
}

/**
 * Implements hook_theme()
 */
function hcbf_home_theme() {
  $themes = array();

  $themes['hcbf_home'] = array(
    'variables' => array(
      'wheat_image' => NULL,
    ),
    'template' => 'templates/hcbf_home',
  );

  return $themes;
}

