<?php
/**
 * @file
 * Contact form functionality for the High Country Beer Fest's websites.
 */

/**
 * Implements hook_permission()
 */
function hcbf_contact_permission() {
  $permissions = array();

  $permissions['access contact form'] = array(
    'title' => t('Access contact form')
  );

  return $permissions;
}

/**
 * Implements hook_menu()
 */
function hcbf_contact_menu() {
  $items = array();

  $items['contact'] = array(
    'title' => t('Contact us'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hcbf_contact_form'),
    'access arguments' => array('access contact form'),
    'file' => 'hcbf_contact.forms.inc'
  );

  return $items;
}

/**
 * Implements hook_mail()
 */
function hcbf_contact_mail($key, &$message, $params) {
  global $user;

  $options = array(
    'langcode' => $message['language']->language,
  );

  switch ($key) {
    case 'contact_message':
      $message['subject'] = t('[@site-name Contact Form]', array('@site-name' => variable_get('site_name', 'Drupal')), $options);
      $message['body'][] = t('@name [@email] sent you the following message:',
        array(
          '@name' => check_plain($params['contact_name']),
          '@email' => check_plain($params['contact_email']),
        ),
      $options);
      $message['body'][] = check_plain($params['contact_message']);
      break;
  }
}

/**
 * Implements a function that sends the mail
 */
function hcbf_contact_send_mail($form_values) {
  $module = 'hcbf_contact';
  $key = 'contact_message';
  $to = 'contact.hcbf@gmail.com';
  $from = check_plain($form_values['contact_email']);
  $params = $form_values;
  $language = language_default();
  $send = TRUE;
  $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);
  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your message has been sent.'));
  }
  else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }
}

