<?php
/**
 * @file
 * Page callbacks for the High Country Craft Food and Beverage Festival's about pages.
 */

/**
 * Page callback for the about page.
 */
function hcbf_about() {
  return theme('hcbf_about');
}

/**
 * Page callback for the about/location page.
 */
function hcbf_about_location() {
  return theme('hcbf_about_location');
}

/**
 * Page callback for the about/exit-strategy page
 */
function hcbf_about_exit() {
  return theme('hcbf_about_exit');
}

