<?php
/**
 * @file
 * Code for the HCBF Sponsors feature.
 */

include_once 'hcbf_sponsors.features.inc';

/**
 * Implements hook_permission()
 */
function hcbf_sponsors_permission() {
  $permissions = array();

  $permissions['manage sponsors'] = array(
    'title' => t('Manage sponsors')
  );

  $permissions['access sponsors'] = array(
    'title' => t('Access sponsors')
  );

  $permissions['access sponsors registration'] = array(
    'title' => t('Access sponsors registration')
  );

  return $permissions;
}

/**
 * Implements hook_menu()
 */
function hcbf_sponsors_menu() {
  $items = array();

  $items['sponsors'] = array(
    'title' => t('Our sponsors'),
    'page callback' => 'hcbf_sponsors',
    'access arguments' => array('access sponsors'),
    'type' => MENU_CALLBACK,
    'file' => 'hcbf_sponsors.pages.inc'
  );

  $items['sponsors/register'] = array(
    'title' => t('Register as a sponsor'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hcbf_sponsors_registration_form'),
    'access arguments' => array('access sponsors registration'),
    'file' => 'hcbf_sponsors.forms.inc'
  );

  return $items;
}

/**
 * Implements hook_theme()
 */
function hcbf_sponsors_theme() {
  $themes = array();

  $themes['hcbf_sponsors'] = array(
    'variables' => array(
      'level_4_sponsors' => NULL,
      'level_3_sponsors' => NULL,
      'level_2_sponsors' => NULL,
      'level_1_sponsors' => NULL,
    ),
    'template' => 'templates/hcbf_sponsors',
  );

  $themes['hcbf_sponsor_registration'] = array(
    'variables' => array(),
    'template' => 'templates/hcbf_sponsor_registration',
  );

  return $themes;
}

